In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(type(arr)) 
lst=[1,23]
print(type(lst))


<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
print("Array arr: ",arr)
# arr.setflags(write=False)
print(" Try to change the value at index 3:")
arr[3] = 11
print(arr)

## Creating Different Dimensional Arrays

In [ ]:
# create 0-Dimensional array
arr0=np.array(42)
print(f"0D-Array: {arr0}\n")

# create 1-Dimensional array
arr1=np.array([1,2,3,4,5])
print(f"1D-Array: {arr1}\n")

# create 2-Dimensional array
arr2=np.array([4,5,6[1,2,3],[]])
print(f"2D-Array: {arr2}\n")

# An n-dimensional array means an array with n-1 dimensions as each element in itself

# create 3-Dimensional array
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],dtype='complex')
print(f"3D-Array: {arr3}\n")


# Checking the dimension of the array
# using ndim attribute
print(f"Dimension of arr3: {arr3.ndim}\n")
print(f"Dimension of arr2: {arr2.ndim}\n")
print(f"Dimension of arr1: {arr1.ndim}\n")
print(f"Dimension of arr0: {arr0.ndim}\n")

In [6]:
# A lot pf people get confused between the shape and the dimension of the array
# Dimension of the array is the number of elements in each axis
# Shape of the array is the number of elements in each dimension

# Checking the shape of the array
# using shape attribute

# 0D-Array: 42
print(f"Shape of arr0: {arr0.shape}\n")

# 1D-Array: [1 2 3 4 5]
print(f"Shape of arr1: {arr1.shape}\n")

# 2D-Array: [[1 2 3] [4 5 6]]
print(f"Shape of arr2: {arr2.shape}\n")

NameError: name 'arr0' is not defined

In [3]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],dtype='complex')
print(f"Shape of arr3: {arr3.shape}\n")
# Printing size (total number of elements) of array 
print("Size of array: ", arr3.size) 


Shape of arr3: (2, 3, 3)

Size of array:  18


In [5]:
# Reshaping the array
# using reshape() method
# Note: We can only reshape the array,
# if the total number of elements in the array is equal
# to the product of the number of elements in each axis

arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(f"Shape of arr4: {arr4.shape}\n")
arr4 = arr4.reshape(6,2)
print(f"Shape of arr4 after reshaping: {arr4.shape}\n")
print(arr4)

Shape of arr4: (12,)

Shape of arr4 after reshaping: (6, 2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [9]:
# Create a sequence of integers
arr = np.arange(10, 110, 10)
print("A sequential array with steps of 10:\n", arr)

A sequential array with steps of 10:
 [ 10  20  30  40  50  60  70  80  90 100]


In [10]:
# Create a sequence of 20 values in range 0 to 4
g = np.linspace(0, 20, 20)
print("A sequential array with 10 values between" "0 and 4:\n", g)

A sequential array with 10 values between0 and 4:
 [ 0.          1.05263158  2.10526316  3.15789474  4.21052632  5.26315789
  6.31578947  7.36842105  8.42105263  9.47368421 10.52631579 11.57894737
 12.63157895 13.68421053 14.73684211 15.78947368 16.84210526 17.89473684
 18.94736842 20.        ]


In [11]:
# The Unknown Dimension
# We are allowed to have one "unknown" dimension

# Example
# Convert 1D array with 6 elements to 3D array with 2x? elements
arr5=np.array([1,2,3,4,5,6,7,8,9])
print(f"Shape of arr5: {arr5.shape}\n")
print(arr5)
print(f"Shape of arr5 after reshaping: {arr5.shape}\n")
# Guess the dimension of the array
print(f"Dimension of arr5: {arr5.ndim}\n")

Shape of arr5: (9,)

[1 2 3 4 5 6 7 8 9]
Shape of arr5 after reshaping: (9,)

Dimension of arr5: 1



In [12]:
# Accessing the elements of the array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Accessing the 2nd element of arr of dim-1: {arr[1]}\n")
print(f"Accessing the 2nd element of arr of dim-2: {arr[2][2]}\n")
print(f"Accessing the 2nd element of arr of dim-3: {arr3[1][1][1]}\n")

Accessing the 2nd element of arr of dim-1: [4 5 6]

Accessing the 2nd element of arr of dim-2: 9

Accessing the 2nd element of arr of dim-3: (5+0j)



In [13]:
# Slicing the array
# [1,2,3,4,5]
print(f"Slicing the array: {arr1[1:4]}\n")

# 2D-Array: [[1 2 3] [4 5 6]]
print(f"Slicing the array: {arr2[1,5:]}\n")

NameError: name 'arr1' is not defined

In [14]:
# [[1 2 3]
#  [4 5 6]]
print(f"Slicing the array: {arr2[0:3,1]}\n")
print(f"Slicing the array: {arr2[0:2,1:3]}\n")

NameError: name 'arr2' is not defined

In [15]:
# Negative Slicing
print(f"Negative Slicing the array: {arr1[-3:-1]}\n")

NameError: name 'arr1' is not defined

In [16]:
def letter_i(size):
    letter_i = np.full((size, size), " ")
    letter_i[0, 0:] = "_"
    letter_i[1, 0:] = "_"
    letter_i[size - 1,0 :] = "_"
    letter_i[size - 2, :] = "_"
    letter_i[1:, size // 2] = "|"
    letter_i[1:, (size // 2)-1] = "|"
    return letter_i
letter_i(8)

array([['_', '_', '_', '_', '_', '_', '_', '_'],
       ['_', '_', '_', '|', '|', '_', '_', '_'],
       [' ', ' ', ' ', '|', '|', ' ', ' ', ' '],
       [' ', ' ', ' ', '|', '|', ' ', ' ', ' '],
       [' ', ' ', ' ', '|', '|', ' ', ' ', ' '],
       [' ', ' ', ' ', '|', '|', ' ', ' ', ' '],
       ['_', '_', '_', '|', '|', '_', '_', '_'],
       ['_', '_', '_', '|', '|', '_', '_', '_']], dtype='<U1')

In [17]:
def letter_e(size):
    letter_e = np.full((size, size), " ")
    letter_e[1:, [1, 2]] = "|"
    letter_e[0, 2:] = "_"
    letter_e[size // 2, 3:] = "_"
    letter_e[size-1, 3:] = "_"
    return letter_e

In [18]:
def print_letters(word):
    for row in word:
        print(" ".join(row))

size = 11
ieee_word = np.concatenate(
    [letter_i(size), letter_e(size), letter_e(size), letter_e(size)], axis=1
)

print_letters(ieee_word)

_ _ _ _ _ _ _ _ _ _ _     _ _ _ _ _ _ _ _ _     _ _ _ _ _ _ _ _ _     _ _ _ _ _ _ _ _ _
_ _ _ _ | | _ _ _ _ _   | |                   | |                   | |                
        | |             | |                   | |                   | |                
        | |             | |                   | |                   | |                
        | |             | |                   | |                   | |                
        | |             | | _ _ _ _ _ _ _ _   | | _ _ _ _ _ _ _ _   | | _ _ _ _ _ _ _ _
        | |             | |                   | |                   | |                
        | |             | |                   | |                   | |                
        | |             | |                   | |                   | |                
_ _ _ _ | | _ _ _ _ _   | |                   | |                   | |                
_ _ _ _ | | _ _ _ _ _   | | _ _ _ _ _ _ _ _   | | _ _ _ _ _ _ _ _   | | _ _ _ _ _ _ _ _
